// export const SIGN_IN = 'SIGN_IN';
// export const SIGN_OUT = 'SIGN_OUT';
export const SEARCH_RELEASES = 'SEARCH_RELEASES';
export const SEARCH_ARTIST = 'SEARCH_ARTIST';
// export const DELETE_STREAM = 'DELETE_STREAM';
// export const FETCH_STREAM = 'FETCH_STREAM';
// export const FETCH_STREAMS = 'FETCH_STREAMS';
// export const EDIT_STREAM = 'EDIT_STREAM';
// export const CREATE_STREAM = 'CREATE_STREAM';